version: "3.1"

services:
  db:
    container_name: db
    image: postgres:12.12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 10s
    restart: on-failure:3
    environment:
      POSTGRES_DB: Bot_DinGo_Dev
      POSTGRES_USER: DinGo_Dev
      POSTGRES_PASSWORD: j8BSGx9rf&8#!pQ*8V*yEAYgm
    network_mode: host
    volumes:
      - ./db:/var/lib/postgresql/data

  dingo:
    container_name: dingo
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:3
    tty: true
    depends_on:
      db:
        condition: service_healthy
    network_mode: host
